[versions]
kotlin = "2.4.21"
activityCompose = "1.13.0"
agp = "9.4.1"
composeBom = "2026.09.00"
kotlinxCoroutinesCore = "1.11.0"
core = "1.19.1"
startupRuntime = "1.2.0"
nmcp = "1.6.2"
annotation = "1.11.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
core = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
material3 = { module = "androidx.compose.material3:material3" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }
gradleup-nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
signing = { id = "signing" }

