name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            aarch64-linux-android
            armv7-linux-androideabi
            x86_64-linux-android

      - name: Build
        run: cargo install cargo-ndk && chmod +x gradlew && ./gradlew :cork:assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: cork
          path: |
            ./cork/build/outputs/aar/cork-release.aar