name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup gradle caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-cork-${{ hashFiles(
            '**/*.gradle.kts',
            '**/gradle-wrapper.properties',
            '**/gradle.properties',
            '**/settings.gradle.kts',
            '**/libs.versions.toml'
            ) }}
          restore-keys: |
            ${{ runner.os }}-cork-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            aarch64-linux-android
            armv7-linux-androideabi
            x86_64-linux-android

      - name: Setup rust caches
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Build
        run: cargo install cargo-ndk && chmod +x gradlew && ./gradlew :cork:assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: cork
          path: |
            ./cork/build/outputs/aar/cork-release.aar