name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup gradle caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-cork-${{ hashFiles(
            '**/*.gradle.kts',
            '**/gradle-wrapper.properties',
            '**/gradle.properties',
            '**/settings.gradle.kts',
            '**/libs.versions.toml'
            ) }}
          restore-keys: |
            ${{ runner.os }}-cork-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            aarch64-linux-android
            armv7-linux-androideabi
            x86_64-linux-android

      - name: Setup rust caches
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: "rust -> target"

      - name: Publish to Maven
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
        run: cargo install cargo-ndk && chmod +x gradlew && ./gradlew publishAllPublicationsToCentralPortal
